export default {
    TEXT_STAGGER_DURATION_S: .15,
    TEXT_APPEAR_DURATION_S: .75,
    SANDWICH_STAGGER_DURATION_S: .11,
    SANDWICH_APPEAR_DURATION_S: .56,
    SCROLL_UP_DURATION_S: 1000,
    DIRECTION_LIST_APPEAR_DURATION_S: .55,
    SCREEN_MD_MIN_PX:768,
};